version: "3.8"

services:
  venus-api:
    container_name: venus-api
    image: shrigorevich/venus-api:dev
    restart: unless-stopped
    ports:
      - "3999:80"
    env_file:
      - venus.env

  postgres-api:
    container_name: postgres-api
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - venus.env

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - venus.env

  kratos-postgres:
    image: postgres:16.1
    env_file:
      - kratos.env
    volumes:
      - ./postgres-kratos-data:/var/lib/postgresql/data
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v1.0.0
    links:
      - kratos-postgres:kratos-postgres
    env_file:
      - kratos.env
    volumes:
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - intranet
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    env_file:
      - kratos.env
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:
