CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS challenge (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id VARCHAR(100) NOT NULL,
  status INTEGER default 1 NOT NULL,
  name VARCHAR (144) NOT NULL,
  description VARCHAR (255),
  start_date DATE NOT NULL,
  end_date DATE
);

CREATE TABLE IF NOT EXISTS challenge_day (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  challenge_id uuid references challenge (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  status INTEGER NOT NULL,
  date DATE NOT NULL,
  UNIQUE (challenge_id, date)
);

CREATE TABLE IF NOT EXISTS user_tag (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS currency (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(3) NOT NULL,
  name VARCHAR(144)
);

CREATE TABLE IF NOT EXISTS purchase (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  date DATE NOT NULL,
  user_id VARCHAR(100) NOT NULL,
  name VARCHAR(144) NOT NULL,
  description VARCHAR(250),
  price DECIMAL NOT NULL,
  unit varchar(20),
  quantity DECIMAL DEFAULT 0,
  discount DECIMAL DEFAULT 0,
  currency_id INT references currency (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS purchase_tag (
  tag_id INT references user_tag (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  purchase_id uuid references purchase (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (tag_id, purchase_id)
);

CREATE TABLE IF NOT EXISTS budget (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(144) NOT NULL,
  amount DECIMAL DEFAULT 1,
  period INT NOT NULL,
  currency_id INT references currency (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS budget_tag (
  budget_id uuid references budget (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  tag_id INT references tag (id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (budget_id, tag_id)
);

